name = "fake-bitcoin-website"
compatibility_date = "2025-09-15"

[env.production.pages_build_output_dir]
dir = "Client/dist"

pages_build_output_dir = "Client/dist"

[build]
command = "cd Client && npm install && npm run build"
cwd = "."
