#
name: Build and Push

# Configures this workflow to run on any branch push, pull requests, and releases
on:
  push:
    branches: ['**']  # Run on all branches
  pull_request:
    branches: ['main']
  release:
    types: [published]  # Trigger on release creation

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Login for main branch pushes OR releases
      - name: Log in to the Container registry
        if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'release'
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about) to extract tags and labels that will be applied to the specified image. The `id` "meta" allows the output of this step to be referenced in a subsequent step. The `images` value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./Server
          push: ${{ (github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'release' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'release'
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
      - name: Setup .NET
        if: github.event_name == 'release'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Build cross-platform binaries
        if: github.event_name == 'release'
        run: |
          # Create release directory
          mkdir -p release
          
          # Build for different platforms using .NET runtime identifiers
          runtimes=(
            "linux-x64"
            "linux-arm64"
            "win-x64"
            "win-arm64"
            "osx-x64"
            "osx-arm64"
          )
          
          for runtime in "${runtimes[@]}"; do
            echo "Building for $runtime..."
            
            # Set appropriate filename
            if [[ "$runtime" == win-* ]]; then
              filename="Server-${runtime}.exe"
            else
              filename="Server-${runtime}"
            fi
            
            # Build and publish for the target runtime
            dotnet publish Server/Server.csproj \
              --configuration Release \
              --runtime $runtime \
              --self-contained true \
              --output "temp-$runtime" \
              /p:PublishSingleFile=true \
              /p:PublishTrimmed=true
            
            if [ $? -ne 0 ]; then
              echo "Build failed for $runtime"
              exit 1
            fi
            
            # Move the executable to release directory with correct name
            if [[ "$runtime" == win-* ]]; then
              mv "temp-$runtime/Server.exe" "release/$filename"
            else
              mv "temp-$runtime/Server" "release/$filename"
            fi
            
            # Clean up temp directory
            rm -rf "temp-$runtime"
          done
          
          # List built files
          ls -la release/

      # Upload binaries to release
      - name: Upload release binaries
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}